// <auto-generated />
using System;
using Avachat.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Avachat.Infra.Migrations
{
    [DbContext(typeof(AvachatContext))]
    [Migration("20260409192042_AddChatModelToAgent")]
    partial class AddChatModelToAgent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Avachat.Domain.Models.Agent", b =>
                {
                    b.Property<long>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AgentId"));

                    b.Property<string>("ChatModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("gpt-4o")
                        .HasColumnName("chat_model");

                    b.Property<bool>("CollectEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("collect_email");

                    b.Property<bool>("CollectName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("collect_name");

                    b.Property<bool>("CollectPhone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("collect_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId")
                        .HasName("avachat_agents_pkey");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("avachat_agents_slug_key");

                    b.ToTable("avachat_agents", (string)null);
                });

            modelBuilder.Entity("Avachat.Domain.Models.ChatMessage", b =>
                {
                    b.Property<long>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ChatMessageId"));

                    b.Property<long?>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer")
                        .HasColumnName("sender_type");

                    b.HasKey("ChatMessageId")
                        .HasName("avachat_chat_messages_pkey");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("avachat_chat_messages", (string)null);
                });

            modelBuilder.Entity("Avachat.Domain.Models.ChatSession", b =>
                {
                    b.Property<long>("ChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ChatSessionId"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_phone");

                    b.HasKey("ChatSessionId")
                        .HasName("avachat_chat_sessions_pkey");

                    b.HasIndex("AgentId");

                    b.ToTable("avachat_chat_sessions", (string)null);
                });

            modelBuilder.Entity("Avachat.Domain.Models.KnowledgeFile", b =>
                {
                    b.Property<long>("KnowledgeFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_file_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("KnowledgeFileId"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_content");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int>("ProcessingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("KnowledgeFileId")
                        .HasName("avachat_knowledge_files_pkey");

                    b.HasIndex("AgentId");

                    b.ToTable("avachat_knowledge_files", (string)null);
                });

            modelBuilder.Entity("Avachat.Domain.Models.ChatMessage", b =>
                {
                    b.HasOne("Avachat.Domain.Models.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("avachat_fk_chat_sessions_chat_messages");

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Avachat.Domain.Models.ChatSession", b =>
                {
                    b.HasOne("Avachat.Domain.Models.Agent", "Agent")
                        .WithMany("ChatSessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("avachat_fk_agents_chat_sessions");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Avachat.Domain.Models.KnowledgeFile", b =>
                {
                    b.HasOne("Avachat.Domain.Models.Agent", "Agent")
                        .WithMany("KnowledgeFiles")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("avachat_fk_agents_knowledge_files");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Avachat.Domain.Models.Agent", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("KnowledgeFiles");
                });

            modelBuilder.Entity("Avachat.Domain.Models.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
